import { Product, Category } from './types';

export const CATEGORIES: Record<string, Category> = {
  aiTools: {
    id: 'c1111111-1111-1111-1111-111111111111',
    name: 'AI Tools',
    slug: 'ai-tools',
    description: 'Discover cutting-edge AI software, autonomous agents, and generative tools to supercharge productivity.',
    seo_title: 'Best AI Tools & Software Directory | DailySoftwareAI',
    seo_description: 'Explore top-rated AI tools, generative platforms, and AI assistants.',
    created_at: new Date().toISOString(),
  },
  businessMarketing: {
    id: 'c2222222-2222-2222-2222-222222222222',
    name: 'Business & Marketing',
    slug: 'business-marketing',
    description: 'Top digital marketing platforms, AI ad generators, and business growth software.',
    seo_title: 'Best Business & Digital Marketing Software | DailySoftwareAI',
    seo_description: 'Compare top marketing suites, ad builders, and client acquisition platforms.',
    created_at: new Date().toISOString(),
  },
  plrContent: {
    id: 'c3333333-3333-3333-3333-333333333333',
    name: 'PLR & Prompt Kits',
    slug: 'plr-content',
    description: 'Private Label Rights assets, Midjourney prompt vaults, coloring books, and digital printables.',
    seo_title: 'Best PLR Products & Prompt Packages | DailySoftwareAI',
    seo_description: 'Find commercial PLR packs, prompt bundles, and printable assets for Etsy & KDP.',
    created_at: new Date().toISOString(),
  },
  softwareApps: {
    id: 'c4444444-4444-4444-4444-444444444444',
    name: 'Software & Apps',
    slug: 'software-apps',
    description: 'Cloud applications, email autoresponders, automation utilities, and SaaS platforms.',
    seo_title: 'Best Cloud Software & Applications | DailySoftwareAI',
    seo_description: 'Browse high-converting SaaS apps, autoresponders, and software solutions.',
    created_at: new Date().toISOString(),
  },
  makeMoneyOnline: {
    id: 'c5555555-5555-5555-5555-555555555555',
    name: 'Make Money Online',
    slug: 'make-money-online',
    description: 'Digital business blueprints, monetization systems, and agency growth software.',
    seo_title: 'Best MMO & Digital Business Blueprints | DailySoftwareAI',
    seo_description: 'Explore verified online business systems, prompt monetization, and agency toolkits.',
    created_at: new Date().toISOString(),
  },
  seo: {
    id: 'c6666666-6666-6666-6666-666666666666',
    name: 'SEO',
    slug: 'seo',
    description: 'Top search engine optimization software, keyword tools, rank trackers, and audit platforms.',
    seo_title: 'Best SEO Software & Ranking Tools | DailySoftwareAI',
    seo_description: 'Compare top SEO tools, audit suites, and keyword research platforms.',
    created_at: new Date().toISOString(),
  },
  automation: {
    id: 'c7777777-7777-7777-7777-777777777777',
    name: 'Automation',
    slug: 'automation',
    description: 'Streamline business processes with no-code automation platforms and workflow tools.',
    seo_title: 'Best Workflow Automation Software | DailySoftwareAI',
    seo_description: 'Find top workflow automation tools and software integration solutions.',
    created_at: new Date().toISOString(),
  },
};

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'p001-odin-ai',
    name: 'Odin AI',
    slug: 'odin-ai',
    tagline: 'Next-Gen AI Workspace & Agentic Assistant by Neil Napier',
    short_description: 'Odin AI is an all-in-one AI workspace and agentic assistant designed to execute complex marketing, content creation, and software workflows in seconds.',
    full_description: 'Created by industry leader Neil Napier, Odin AI combines multi-model intelligence, automated content generation, and deep workflow integration. It serves as a central AI operating system for agencies, digital marketers, and solopreneurs wanting to streamline their daily operations without juggling multiple AI subscriptions.',
    logo_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=150&q=80',
    featured_image_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80',
    official_website_url: 'https://jvz5.com/c/3374691/443535',
    launch_date: '2026-07-20',
    launch_time: '10:00:00',
    launch_timezone: 'America/New_York',
    pricing_type: 'lifetime',
    price_text: '$37 One-Time Commercial Deal',
    rating: 4.9,
    editor_score: 9.7,
    current_rank: 1,
    affiliate_network: 'jvzoo',
    is_featured: true,
    is_trending: true,
    is_top_pick: true,
    status: 'published',
    seo_title: 'Odin AI Review 2026: Features, Pricing & Neil Napier Deal | DailySoftwareAI',
    seo_description: 'Comprehensive review of Odin AI by Neil Napier. Learn how this all-in-one AI agent workspace automates content and marketing workflows.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date().toISOString(),
    categories: [CATEGORIES.aiTools, CATEGORIES.softwareApps],
    affiliate_links: [
      {
        id: 'link-001',
        product_id: 'p001-odin-ai',
        network: 'jvzoo',
        url: 'https://jvz5.com/c/3374691/443535',
        status: 'active',
        is_primary: true,
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'p002-trafficos-ai',
    name: 'TrafficOS AI (Bundle)',
    slug: 'trafficos-ai-bundle',
    tagline: 'Automated Viral Video & Traffic Generation Engine by Jono Armstrong',
    short_description: 'TrafficOS AI is Jono Armstrong’s flagship traffic suite that automates buyer traffic extraction across viral video platforms like YouTube Shorts and TikTok.',
    full_description: 'TrafficOS AI Bundle equips marketers with automated short-form video creation, viral content curation, and multi-channel social distribution. Built by top affiliate Jono Armstrong, it turns video views into instant commission streams.',
    logo_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=150&q=80',
    featured_image_url: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80',
    official_website_url: 'https://jvz4.com/c/3374691/443011/',
    launch_date: '2026-07-21',
    launch_time: '11:00:00',
    launch_timezone: 'America/New_York',
    pricing_type: 'lifetime',
    price_text: '$47 Bundle Special Deal',
    rating: 4.8,
    editor_score: 9.5,
    current_rank: 2,
    affiliate_network: 'jvzoo',
    is_featured: true,
    is_trending: true,
    is_top_pick: false,
    status: 'published',
    seo_title: 'TrafficOS AI Bundle Review & Discount | DailySoftwareAI',
    seo_description: 'Read our review of TrafficOS AI by Jono Armstrong. Automate viral video creation and traffic generation easily.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date().toISOString(),
    categories: [CATEGORIES.businessMarketing, CATEGORIES.aiTools],
    affiliate_links: [
      {
        id: 'link-002',
        product_id: 'p002-trafficos-ai',
        network: 'jvzoo',
        url: 'https://jvz4.com/c/3374691/443011/',
        status: 'active',
        is_primary: true,
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'p003-327-trivia-prompts',
    name: '327 Fun Trivia Prompts for Kids',
    slug: '327-fun-trivia-prompts-for-kids',
    tagline: 'Unrestricted PLR Kids Trivia Prompt Collection for KDP & Printables',
    short_description: '327 handcrafted, highly engaging trivia prompts formatted for children’s book creators, KDP self-publishers, and Etsy printable sellers.',
    full_description: 'Created by AJ, this commercial PLR package provides 327 fun, educational trivia prompts. Perfect for self-publishers looking to build children’s activity books, trivia cards, or digital downloads with full resell rights.',
    logo_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=150&q=80',
    featured_image_url: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=1200&q=80',
    official_website_url: 'https://warriorplus.com/o2/a/bjr9kby/0',
    launch_date: '2026-07-22',
    launch_time: '09:00:00',
    launch_timezone: 'America/New_York',
    pricing_type: 'lifetime',
    price_text: '$17 Unrestricted PLR License',
    rating: 4.7,
    editor_score: 9.2,
    current_rank: 3,
    affiliate_network: 'warriorplus',
    is_featured: false,
    is_trending: true,
    is_top_pick: false,
    status: 'published',
    seo_title: '327 Fun Trivia Prompts for Kids PLR Review | DailySoftwareAI',
    seo_description: 'Get full PLR rights to 327 children trivia prompts for KDP and Etsy digital products.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date().toISOString(),
    categories: [CATEGORIES.plrContent],
    affiliate_links: [
      {
        id: 'link-003',
        product_id: 'p003-327-trivia-prompts',
        network: 'warriorplus',
        url: 'https://warriorplus.com/o2/a/bjr9kby/0',
        status: 'active',
        is_primary: true,
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'p004-promptoriakit',
    name: 'PromptoriaKit - 10 Complete Story Coloring Books',
    slug: 'promptoriakit-10-complete-story-coloring-books',
    tagline: '10 Ready-to-Publish Children Story Coloring Books with Commercial PLR',
    short_description: 'Ethan Truong’s complete publishing pack featuring 10 full story coloring books with prompt source files and high-res vector graphics.',
    full_description: 'PromptoriaKit gives self-publishers and digital product creators 10 turnkey children’s story coloring books. Includes Midjourney prompts, high-resolution pages, and unrestricted PLR licensing for instant publishing on Amazon KDP and Etsy.',
    logo_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=150&q=80',
    featured_image_url: 'https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?auto=format&fit=crop&w=1200&q=80',
    official_website_url: 'https://warriorplus.com/o2/a/r0lnp2v/0',
    launch_date: '2026-07-23',
    launch_time: '10:00:00',
    launch_timezone: 'America/New_York',
    pricing_type: 'lifetime',
    price_text: '$27 Commercial PLR Package',
    rating: 4.8,
    editor_score: 9.6,
    current_rank: 4,
    affiliate_network: 'warriorplus',
    is_featured: true,
    is_trending: true,
    is_top_pick: false,
    status: 'published',
    seo_title: 'PromptoriaKit 10 Coloring Books PLR Review | DailySoftwareAI',
    seo_description: 'Explore Ethan Truong’s PromptoriaKit. 10 complete story coloring books with commercial PLR rights.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date().toISOString(),
    categories: [CATEGORIES.plrContent, CATEGORIES.aiTools],
    affiliate_links: [
      {
        id: 'link-004',
        product_id: 'p004-promptoriakit',
        network: 'warriorplus',
        url: 'https://warriorplus.com/o2/a/r0lnp2v/0',
        status: 'active',
        is_primary: true,
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'p005-cozy-eggshell',
    name: 'Cozy Eggshell Worlds Coloring Pack (PLR)',
    slug: 'cozy-eggshell-worlds-coloring-pack-plr',
    tagline: 'Whimsical Miniature Eggshell Landscape Coloring Pages for KDP & Etsy',
    short_description: 'A unique collection of high-resolution cozy eggshell world coloring pages designed by Cani Miyuki with full PLR commercial rights.',
    full_description: 'Cozy Eggshell Worlds Coloring Pack brings adorable miniature landscape coloring pages perfect for adult relaxing coloring books, printables, and Etsy digital stores.',
    logo_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=150&q=80',
    featured_image_url: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=1200&q=80',
    official_website_url: 'https://warriorplus.com/o2/a/nw89jwr/0',
    launch_date: '2026-07-24',
    launch_time: '09:00:00',
    launch_timezone: 'America/New_York',
    pricing_type: 'lifetime',
    price_text: '$19 PLR License Deal',
    rating: 4.7,
    editor_score: 9.3,
    current_rank: 5,
    affiliate_network: 'warriorplus',
    is_featured: false,
    is_trending: false,
    is_top_pick: false,
    status: 'published',
    seo_title: 'Cozy Eggshell Worlds Coloring Pack PLR Review | DailySoftwareAI',
    seo_description: 'Get Cani Miyuki’s Cozy Eggshell Worlds Coloring Pack with commercial PLR rights.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date().toISOString(),
    categories: [CATEGORIES.plrContent],
    affiliate_links: [
      {
        id: 'link-005',
        product_id: 'p005-cozy-eggshell',
        network: 'warriorplus',
        url: 'https://warriorplus.com/o2/a/nw89jwr/0',
        status: 'active',
        is_primary: true,
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'p006-ephemera-prompts',
    name: 'Printable Ephemera Prompts',
    slug: 'printable-ephemera-prompts',
    tagline: 'Vintage Ephemera Prompt Vault for Junk Journals & Digital Crafts',
    short_description: 'Dexter Dang’s curated AI prompt collection for generating vintage labels, stamps, antique receipts, and junk journal graphics.',
    full_description: 'Printable Ephemera Prompts allows digital craft creators and Etsy sellers to instantly generate unlimited vintage labels, tickets, collage sheets, and ephemera graphics using Midjourney and DALL-E.',
    logo_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=150&q=80',
    featured_image_url: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=1200&q=80',
    official_website_url: 'https://warriorplus.com/o2/a/fnn9d5f/0',
    launch_date: '2026-07-25',
    launch_time: '10:00:00',
    launch_timezone: 'America/New_York',
    pricing_type: 'lifetime',
    price_text: '$17 Commercial License',
    rating: 4.6,
    editor_score: 9.2,
    current_rank: 6,
    affiliate_network: 'warriorplus',
    is_featured: false,
    is_trending: true,
    is_top_pick: false,
    status: 'published',
    seo_title: 'Printable Ephemera Prompts Review & Deal | DailySoftwareAI',
    seo_description: 'Dexter Dang’s Printable Ephemera Prompts review. Generate unlimited vintage junk journal assets with AI.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date().toISOString(),
    categories: [CATEGORIES.plrContent, CATEGORIES.aiTools],
    affiliate_links: [
      {
        id: 'link-006',
        product_id: 'p006-ephemera-prompts',
        network: 'warriorplus',
        url: 'https://warriorplus.com/o2/a/fnn9d5f/0',
        status: 'active',
        is_primary: true,
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'p007-ai-adsagency-builder',
    name: 'AI AdsAgency Builder',
    slug: 'ai-adsagency-builder',
    tagline: 'Turnkey AI Ad Agency Creation Platform & Client Finder Suite',
    short_description: 'Build and run a profitable AI ad agency with automated Facebook, Google, and TikTok ad creative tools plus client acquisition features.',
    full_description: 'AI AdsAgency Builder automates high-converting video and image ad creation for multi-platform marketing. Includes done-for-you agency client proposals, agreement templates, and lead generation.',
    logo_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=150&q=80',
    featured_image_url: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80',
    official_website_url: 'https://launchpadjv.com/o/383/21932',
    launch_date: '2026-07-25',
    launch_time: '11:00:00',
    launch_timezone: 'America/New_York',
    pricing_type: 'lifetime',
    price_text: '$37 Commercial Agency License',
    rating: 4.9,
    editor_score: 9.7,
    current_rank: 7,
    affiliate_network: 'launchpad',
    is_featured: true,
    is_trending: true,
    is_top_pick: false,
    status: 'published',
    seo_title: 'AI AdsAgency Builder Review 2026 | DailySoftwareAI',
    seo_description: 'In-depth review of AI AdsAgency Builder. Build an automated ad agency in minutes with AI.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date().toISOString(),
    categories: [CATEGORIES.businessMarketing, CATEGORIES.aiTools],
    affiliate_links: [
      {
        id: 'link-007',
        product_id: 'p007-ai-adsagency-builder',
        network: 'launchpad',
        url: 'https://launchpadjv.com/o/383/21932',
        status: 'active',
        is_primary: true,
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'p008-bookmint',
    name: 'BookMint',
    slug: 'bookmint',
    tagline: 'AI Ebook & AudioBook Creator Platform by Seun Ogundele',
    short_description: 'BookMint by Seun Ogundele crafts complete ebooks, flipbooks, and voiceover audiobooks in under 60 seconds.',
    full_description: 'BookMint eliminates writing barriers by generating full-length fiction/non-fiction books, formatting designs, cover art, and narration for Amazon KDP and self-publishing streams.',
    logo_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=150&q=80',
    featured_image_url: 'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?auto=format&fit=crop&w=1200&q=80',
    official_website_url: 'https://launchpadjv.com/o/397/21932',
    launch_date: '2026-07-24',
    launch_time: '10:00:00',
    launch_timezone: 'America/New_York',
    pricing_type: 'lifetime',
    price_text: '$27 Launch Special Deal',
    rating: 4.8,
    editor_score: 9.4,
    current_rank: 8,
    affiliate_network: 'launchpad',
    is_featured: true,
    is_trending: true,
    is_top_pick: false,
    status: 'published',
    seo_title: 'BookMint AI Ebook Creator Review | DailySoftwareAI',
    seo_description: 'Read our review of Seun Ogundele’s BookMint. Create AI ebooks and audiobooks automatically.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date().toISOString(),
    categories: [CATEGORIES.businessMarketing, CATEGORIES.aiTools],
    affiliate_links: [
      {
        id: 'link-008',
        product_id: 'p008-bookmint',
        network: 'launchpad',
        url: 'https://launchpadjv.com/o/397/21932',
        status: 'active',
        is_primary: true,
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'p009-the-superkids-ai',
    name: 'The SuperKids AI',
    slug: 'the-superkids-ai',
    tagline: 'AI Educational Game & Interactive Learning Content Suite for Kids',
    short_description: 'Ashish Kathiriya’s AI platform for creating customized children’s learning games, storybooks, and interactive quizzes.',
    full_description: 'The SuperKids AI allows parents, educators, and content creators to build engaging educational games, animated stories, and gamified study sheets in seconds.',
    logo_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=150&q=80',
    featured_image_url: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1200&q=80',
    official_website_url: 'https://warriorplus.com/o2/a/zt50784/0',
    launch_date: '2026-07-23',
    launch_time: '09:00:00',
    launch_timezone: 'America/New_York',
    pricing_type: 'lifetime',
    price_text: '$37 Commercial License',
    rating: 4.7,
    editor_score: 9.3,
    current_rank: 9,
    affiliate_network: 'warriorplus',
    is_featured: false,
    is_trending: false,
    is_top_pick: false,
    status: 'published',
    seo_title: 'The SuperKids AI Review & Deal | DailySoftwareAI',
    seo_description: 'Ashish Kathiriya’s The SuperKids AI review. Build AI children educational games effortlessly.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date().toISOString(),
    categories: [CATEGORIES.aiTools, CATEGORIES.softwareApps],
    affiliate_links: [
      {
        id: 'link-009',
        product_id: 'p009-the-superkids-ai',
        network: 'warriorplus',
        url: 'https://warriorplus.com/o2/a/zt50784/0',
        status: 'active',
        is_primary: true,
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'p010-nicheflow-ai',
    name: 'NicheFlow AI',
    slug: 'nicheflow-ai',
    tagline: 'AI Internet Marketing & Niche Funnel Automation Software',
    short_description: 'Automates niche research, sales page copywriting, lead magnets, and email sequences in any profitable market segment.',
    full_description: 'NicheFlow AI helps digital marketers uncover untapped sub-niches and generate complete end-to-end sales funnels with AI copywriting and landing page generation.',
    logo_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=150&q=80',
    featured_image_url: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80',
    official_website_url: 'https://warriorplus.com/o2/a/gpbghnr/0',
    launch_date: '2026-07-22',
    launch_time: '10:00:00',
    launch_timezone: 'America/New_York',
    pricing_type: 'lifetime',
    price_text: '$27 Launch Special',
    rating: 4.6,
    editor_score: 9.2,
    current_rank: 10,
    affiliate_network: 'warriorplus',
    is_featured: false,
    is_trending: true,
    is_top_pick: false,
    status: 'published',
    seo_title: 'NicheFlow AI Review & Pricing | DailySoftwareAI',
    seo_description: 'Automate niche marketing and funnel creation with marcuszane’s NicheFlow AI.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date().toISOString(),
    categories: [CATEGORIES.businessMarketing, CATEGORIES.aiTools],
    affiliate_links: [
      {
        id: 'link-010',
        product_id: 'p010-nicheflow-ai',
        network: 'warriorplus',
        url: 'https://warriorplus.com/o2/a/gpbghnr/0',
        status: 'active',
        is_primary: true,
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'p011-ecomrobots-ai',
    name: 'EcomRobots AI',
    slug: 'ecomrobots-ai',
    tagline: 'Autonomous E-commerce Store Builder & Product Sourcing Engine',
    short_description: 'Rudy Rudra’s automated store builder that finds winning e-commerce products and builds fully monetized storefronts.',
    full_description: 'EcomRobots AI automates product research, supplier sourcing, high-converting product description writing, and storefront design for dropshipping & e-com entrepreneurs.',
    logo_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=150&q=80',
    featured_image_url: 'https://images.unsplash.com/photo-1556742049-0a670fc80799?auto=format&fit=crop&w=1200&q=80',
    official_website_url: 'https://launchpadjv.com/o/405/21932',
    launch_date: '2026-07-25',
    launch_time: '11:00:00',
    launch_timezone: 'America/New_York',
    pricing_type: 'lifetime',
    price_text: '$29 One-Time Deal',
    rating: 4.8,
    editor_score: 9.5,
    current_rank: 11,
    affiliate_network: 'launchpad',
    is_featured: true,
    is_trending: false,
    is_top_pick: false,
    status: 'published',
    seo_title: 'EcomRobots AI Review & Deal | DailySoftwareAI',
    seo_description: 'Rudy Rudra’s EcomRobots AI review. Build automated e-commerce stores in minutes.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date().toISOString(),
    categories: [CATEGORIES.softwareApps, CATEGORIES.aiTools],
    affiliate_links: [
      {
        id: 'link-011',
        product_id: 'p011-ecomrobots-ai',
        network: 'launchpad',
        url: 'https://launchpadjv.com/o/405/21932',
        status: 'active',
        is_primary: true,
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'p012-claw-agents-ai',
    name: 'Claw Agents AI Xtreme',
    slug: 'claw-agents-ai-xtreme',
    tagline: 'Autonomous AI Multi-Agent Network for Online Profit Automation',
    short_description: 'Deploy autonomous AI agents that collaborate to execute digital marketing, client outreach, and affiliate campaigns 24/7.',
    full_description: 'Yogesh Agarwal’s Claw Agents AI Xtreme assigns specialized AI agents to handle copywriting, graphic design, lead generation, and social media posting simultaneously.',
    logo_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=150&q=80',
    featured_image_url: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=1200&q=80',
    official_website_url: 'https://jvz1.com/c/3374691/444721',
    launch_date: '2026-07-21',
    launch_time: '10:00:00',
    launch_timezone: 'America/New_York',
    pricing_type: 'lifetime',
    price_text: '$37 Special Deal',
    rating: 4.9,
    editor_score: 9.6,
    current_rank: 12,
    affiliate_network: 'jvzoo',
    is_featured: true,
    is_trending: true,
    is_top_pick: false,
    status: 'published',
    seo_title: 'Claw Agents AI Xtreme Review | DailySoftwareAI',
    seo_description: 'Deploy Yogesh Agarwal’s multi-agent AI network for digital marketing and profit automation.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date().toISOString(),
    categories: [CATEGORIES.makeMoneyOnline, CATEGORIES.aiTools],
    affiliate_links: [
      {
        id: 'link-012',
        product_id: 'p012-claw-agents-ai',
        network: 'jvzoo',
        url: 'https://jvz1.com/c/3374691/444721',
        status: 'active',
        is_primary: true,
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'p013-prompt-profit-blueprint',
    name: 'AI Prompt Profit Blueprint',
    slug: 'ai-prompt-profit-blueprint',
    tagline: 'Complete System to Package & Sell High-Ticket Prompt Packs',
    short_description: 'John Annavi’s step-by-step blueprint and software suite for building a high-margin prompt engineering business.',
    full_description: 'AI Prompt Profit Blueprint provides tested prompt templates, monetization strategy maps, and marketing assets to profit from selling prompts on Gumroad, Etsy, and private marketplaces.',
    logo_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=150&q=80',
    featured_image_url: 'https://images.unsplash.com/photo-1553877522-43269d4ea984?auto=format&fit=crop&w=1200&q=80',
    official_website_url: 'https://jvz1.com/c/3374691/445667',
    launch_date: '2026-07-20',
    launch_time: '11:00:00',
    launch_timezone: 'America/New_York',
    pricing_type: 'lifetime',
    price_text: '$27 Lifetime Access',
    rating: 4.7,
    editor_score: 9.3,
    current_rank: 13,
    affiliate_network: 'jvzoo',
    is_featured: false,
    is_trending: false,
    is_top_pick: false,
    status: 'published',
    seo_title: 'AI Prompt Profit Blueprint Review | DailySoftwareAI',
    seo_description: 'John Annavi’s blueprint for packaging and monetizing high-ticket AI prompt libraries.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date().toISOString(),
    categories: [CATEGORIES.makeMoneyOnline, CATEGORIES.plrContent],
    affiliate_links: [
      {
        id: 'link-013',
        product_id: 'p013-prompt-profit-blueprint',
        network: 'jvzoo',
        url: 'https://jvz1.com/c/3374691/445667',
        status: 'active',
        is_primary: true,
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'p014-aigency-valet',
    name: 'Aigency Valet vDFY Pro',
    slug: 'aigency-valet-vdfy-pro',
    tagline: 'Done-For-You AI Agency Infrastructure & Client Fulfillment Engine',
    short_description: 'Joshua Zamora’s DFY agency platform that delivers pre-built AI service workflows and automated client onboarding.',
    full_description: 'Aigency Valet vDFY Pro arms agency owners with pre-configured AI bots, sales presentations, proposal templates, and client management software built by Joshua Zamora.',
    logo_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=150&q=80',
    featured_image_url: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1200&q=80',
    official_website_url: 'https://jvz1.com/c/3374691/445089',
    launch_date: '2026-07-19',
    launch_time: '11:00:00',
    launch_timezone: 'America/New_York',
    pricing_type: 'lifetime',
    price_text: '$47 Commercial Agency License',
    rating: 4.9,
    editor_score: 9.7,
    current_rank: 14,
    affiliate_network: 'jvzoo',
    is_featured: true,
    is_trending: true,
    is_top_pick: false,
    status: 'published',
    seo_title: 'Aigency Valet vDFY Pro Review | DailySoftwareAI',
    seo_description: 'Joshua Zamora’s Aigency Valet vDFY Pro review. Turnkey AI agency fulfillment software.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date().toISOString(),
    categories: [CATEGORIES.businessMarketing, CATEGORIES.makeMoneyOnline],
    affiliate_links: [
      {
        id: 'link-014',
        product_id: 'p014-aigency-valet',
        network: 'jvzoo',
        url: 'https://jvz1.com/c/3374691/445089',
        status: 'active',
        is_primary: true,
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'p015-leadpilot-ai',
    name: 'LeadPilot AI',
    slug: 'leadpilot-ai',
    tagline: 'Autonomous B2B Lead Scraping & AI Outreach Agent',
    short_description: 'Extract verified B2B leads from LinkedIn and Google Maps, then launch hyper-personalized AI cold email sequences automatically.',
    full_description: 'LeadPilot AI by ClicksBotz revolutionizes prospecting with real-time contact validation, AI email writing, and automated inbox warmup.',
    logo_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=150&q=80',
    featured_image_url: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=1200&q=80',
    official_website_url: 'https://launchpadjv.com/o/408/21932',
    launch_date: '2026-07-24',
    launch_time: '10:00:00',
    launch_timezone: 'America/New_York',
    pricing_type: 'lifetime',
    price_text: '$37 Launch Deal',
    rating: 4.8,
    editor_score: 9.4,
    current_rank: 15,
    affiliate_network: 'launchpad',
    is_featured: false,
    is_trending: true,
    is_top_pick: false,
    status: 'published',
    seo_title: 'LeadPilot AI Review & Deal | DailySoftwareAI',
    seo_description: 'ClicksBotz LeadPilot AI review. Automate B2B lead generation and cold outreach effortlessly.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date().toISOString(),
    categories: [CATEGORIES.softwareApps, CATEGORIES.businessMarketing],
    affiliate_links: [
      {
        id: 'link-015',
        product_id: 'p015-leadpilot-ai',
        network: 'launchpad',
        url: 'https://launchpadjv.com/o/408/21932',
        status: 'active',
        is_primary: true,
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'p016-ai-mailer',
    name: 'AI Mailer',
    slug: 'ai-mailer',
    tagline: 'AI Autoresponder with Unlimited Sending & Smart Inbox Delivery',
    short_description: 'Next-gen email autoresponder with built-in AI copywriting, spam checker, and high deliverability SMTP infrastructure.',
    full_description: 'AI Mailer by Amit Gaikwad and Anirudh Baavra lets email marketers send unlimited emails without monthly subscription fees, featuring AI subject line optimization and automated list cleaning.',
    logo_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=150&q=80',
    featured_image_url: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=1200&q=80',
    official_website_url: 'https://launchpadjv.com/o/411/21932',
    launch_date: '2026-07-23',
    launch_time: '11:00:00',
    launch_timezone: 'America/New_York',
    pricing_type: 'lifetime',
    price_text: '$27 Commercial Deal',
    rating: 4.8,
    editor_score: 9.5,
    current_rank: 16,
    affiliate_network: 'launchpad',
    is_featured: true,
    is_trending: true,
    is_top_pick: false,
    status: 'published',
    seo_title: 'AI Mailer Review 2026 | DailySoftwareAI',
    seo_description: 'Amit Gaikwad & Anirudh Baavra AI Mailer review. Send unlimited autoresponder emails with AI.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date().toISOString(),
    categories: [CATEGORIES.softwareApps, CATEGORIES.businessMarketing],
    affiliate_links: [
      {
        id: 'link-016',
        product_id: 'p016-ai-mailer',
        network: 'launchpad',
        url: 'https://launchpadjv.com/o/411/21932',
        status: 'active',
        is_primary: true,
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'p017-codex-course-machine',
    name: 'Codex Course Machine',
    slug: 'codex-course-machine',
    tagline: 'Instant AI Online Course Creator & Video Lesson Generator',
    short_description: 'Turn any topic or keyword into a complete video course with slides, AI voiceover, workbooks, and quizzes in minutes.',
    full_description: 'Codex Course Machine by Mohith Mohan builds complete e-learning courses ready to publish on Udemy, Teachable, or your own membership site.',
    logo_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=150&q=80',
    featured_image_url: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80',
    official_website_url: 'https://jvz7.com/c/3374691/444237/',
    launch_date: '2026-07-22',
    launch_time: '09:00:00',
    launch_timezone: 'America/New_York',
    pricing_type: 'lifetime',
    price_text: '$37 Special Offer',
    rating: 4.7,
    editor_score: 9.3,
    current_rank: 17,
    affiliate_network: 'jvzoo',
    is_featured: false,
    is_trending: false,
    is_top_pick: false,
    status: 'published',
    seo_title: 'Codex Course Machine Review | DailySoftwareAI',
    seo_description: 'Mohith Mohan’s Codex Course Machine review. Create AI video courses automatically.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date().toISOString(),
    categories: [CATEGORIES.makeMoneyOnline, CATEGORIES.aiTools],
    affiliate_links: [
      {
        id: 'link-017',
        product_id: 'p017-codex-course-machine',
        network: 'jvzoo',
        url: 'https://jvz7.com/c/3374691/444237/',
        status: 'active',
        is_primary: true,
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'p018-healtrics',
    name: 'Healtrics - AI-Powered Health Assistant',
    slug: 'healtrics-ai-powered-health-assistant',
    tagline: 'Personalized AI Health Insights & Wellness Tracker Platform',
    short_description: 'Albinolabs’ smart AI assistant for meal planning, symptom tracking, fitness routines, and health optimization.',
    full_description: 'Healtrics provides personalized nutrition guidance, AI lab report analysis, workout plan generation, and daily health habit tracking.',
    logo_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=150&q=80',
    featured_image_url: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=1200&q=80',
    official_website_url: 'https://jvz3.com/c/3374691/444615/',
    launch_date: '2026-07-21',
    launch_time: '10:00:00',
    launch_timezone: 'America/New_York',
    pricing_type: 'lifetime',
    price_text: '$29 Lifetime Plan',
    rating: 4.7,
    editor_score: 9.2,
    current_rank: 18,
    affiliate_network: 'jvzoo',
    is_featured: false,
    is_trending: false,
    is_top_pick: false,
    status: 'published',
    seo_title: 'Healtrics AI Health Assistant Review | DailySoftwareAI',
    seo_description: 'Albinolabs Healtrics review. Personalized AI wellness and health optimization tool.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date().toISOString(),
    categories: [CATEGORIES.aiTools, CATEGORIES.softwareApps],
    affiliate_links: [
      {
        id: 'link-018',
        product_id: 'p018-healtrics',
        network: 'jvzoo',
        url: 'https://jvz3.com/c/3374691/444615/',
        status: 'active',
        is_primary: true,
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'p019-publibot',
    name: 'PubliBOT',
    slug: 'publibot',
    tagline: 'Automated Social Media Publishing & Multi-Platform Syndication Bot',
    short_description: 'Schedule and auto-post AI generated content across Instagram, YouTube Shorts, TikTok, Facebook, and Pinterest.',
    full_description: 'PubliBOT by Seun Ogundele automates social media presence by creating viral clips, graphics, and captions, then scheduling them across all major platforms.',
    logo_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=150&q=80',
    featured_image_url: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?auto=format&fit=crop&w=1200&q=80',
    official_website_url: 'https://launchpadjv.com/o/79/21932',
    launch_date: '2026-07-20',
    launch_time: '11:00:00',
    launch_timezone: 'America/New_York',
    pricing_type: 'lifetime',
    price_text: '$27 Launch Special',
    rating: 4.8,
    editor_score: 9.4,
    current_rank: 19,
    affiliate_network: 'launchpad',
    is_featured: false,
    is_trending: true,
    is_top_pick: false,
    status: 'published',
    seo_title: 'PubliBOT Review & Deal | DailySoftwareAI',
    seo_description: 'Seun Ogundele PubliBOT review. Automate social media scheduling and content syndication.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date().toISOString(),
    categories: [CATEGORIES.softwareApps, CATEGORIES.businessMarketing],
    affiliate_links: [
      {
        id: 'link-019',
        product_id: 'p019-publibot',
        network: 'launchpad',
        url: 'https://launchpadjv.com/o/79/21932',
        status: 'active',
        is_primary: true,
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'p020-geminai-35',
    name: 'GeminAI 3.5',
    slug: 'geminai-35',
    tagline: 'Multimodal AI Suite Powered by Next-Gen LLM Architectures',
    short_description: 'Mike & Radu’s flagship cloud app that unleashes multimodal text, image, code, and video generation capabilities.',
    full_description: 'GeminAI 3.5 gives users unlimited access to high-tier AI generation without recurring monthly API keys or subscription fees.',
    logo_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=150&q=80',
    featured_image_url: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&w=1200&q=80',
    official_website_url: 'https://launchpadjv.com/o/406/21932',
    launch_date: '2026-07-25',
    launch_time: '10:00:00',
    launch_timezone: 'America/New_York',
    pricing_type: 'lifetime',
    price_text: '$19 Lifetime Unlimited',
    rating: 4.9,
    editor_score: 9.6,
    current_rank: 20,
    affiliate_network: 'launchpad',
    is_featured: true,
    is_trending: true,
    is_top_pick: false,
    status: 'published',
    seo_title: 'GeminAI 3.5 Review | DailySoftwareAI',
    seo_description: 'Mike & Radu GeminAI 3.5 review. Multimodal AI text, image, and video generation app.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date().toISOString(),
    categories: [CATEGORIES.aiTools, CATEGORIES.softwareApps],
    affiliate_links: [
      {
        id: 'link-020',
        product_id: 'p020-geminai-35',
        network: 'launchpad',
        url: 'https://launchpadjv.com/o/406/21932',
        status: 'active',
        is_primary: true,
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'p021-profitbot',
    name: 'ProfitBOT',
    slug: 'profitbot',
    tagline: 'Automated Affiliate Site & Monetized Traffic Bot by Seun Ogundele',
    short_description: 'Seun Ogundele’s hands-free affiliate app that creates auto-updating product review websites and drives targeted traffic.',
    full_description: 'ProfitBOT automatically fetches hot trending products from ClickBank, JVZoo, and WarriorPlus, creates SEO reviews, and embeds your affiliate links.',
    logo_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=150&q=80',
    featured_image_url: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80',
    official_website_url: 'https://launchpadjv.com/o/421/21932',
    launch_date: '2026-07-24',
    launch_time: '09:00:00',
    launch_timezone: 'America/New_York',
    pricing_type: 'lifetime',
    price_text: '$27 Commercial License',
    rating: 4.7,
    editor_score: 9.3,
    current_rank: 21,
    affiliate_network: 'launchpad',
    is_featured: false,
    is_trending: true,
    is_top_pick: false,
    status: 'published',
    seo_title: 'ProfitBOT Review & Deal | DailySoftwareAI',
    seo_description: 'Seun Ogundele ProfitBOT review. Automate affiliate review sites and monetize traffic.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date().toISOString(),
    categories: [CATEGORIES.softwareApps, CATEGORIES.businessMarketing],
    affiliate_links: [
      {
        id: 'link-021',
        product_id: 'p021-profitbot',
        network: 'launchpad',
        url: 'https://launchpadjv.com/o/421/21932',
        status: 'active',
        is_primary: true,
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'p022-claudfable-ai',
    name: 'ClaudFable AI',
    slug: 'claudfable-ai',
    tagline: 'AI Storyteller & Illustrated Children Book Creator by Pranshu Gupta',
    short_description: 'Generate captivating children’s fables, storybooks, and fantasy tales with matching AI illustrations in seconds.',
    full_description: 'ClaudFable AI by Pranshu Gupta transforms ideas into complete formatted books with custom character consistency for Amazon KDP publishing.',
    logo_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=150&q=80',
    featured_image_url: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=1200&q=80',
    official_website_url: 'https://launchpadjv.com/o/417/21932',
    launch_date: '2026-07-23',
    launch_time: '10:00:00',
    launch_timezone: 'America/New_York',
    pricing_type: 'lifetime',
    price_text: '$37 Special Commercial',
    rating: 4.8,
    editor_score: 9.5,
    current_rank: 22,
    affiliate_network: 'launchpad',
    is_featured: true,
    is_trending: false,
    is_top_pick: false,
    status: 'published',
    seo_title: 'ClaudFable AI Review | DailySoftwareAI',
    seo_description: 'Pranshu Gupta ClaudFable AI review. Create illustrated children books with AI.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date().toISOString(),
    categories: [CATEGORIES.aiTools, CATEGORIES.softwareApps],
    affiliate_links: [
      {
        id: 'link-022',
        product_id: 'p022-claudfable-ai',
        network: 'launchpad',
        url: 'https://launchpadjv.com/o/417/21932',
        status: 'active',
        is_primary: true,
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'p023-facelessforge-ai',
    name: 'FacelessForge AI',
    slug: 'facelessforge-ai',
    tagline: 'Faceless YouTube & Short-Form Video Automation Factory by Andrew Darius',
    short_description: 'Andrew Darius’s AI video maker that creates faceless viral videos for Shorts, Reels, and YouTube with human-like voiceovers.',
    full_description: 'FacelessForge AI crafts video scripts, generates relevant stock/AI footage, adds dynamic subtitles, and renders ready-to-upload viral videos.',
    logo_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=150&q=80',
    featured_image_url: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?auto=format&fit=crop&w=1200&q=80',
    official_website_url: 'https://jvz4.com/c/3374691/445415',
    launch_date: '2026-07-22',
    launch_time: '11:00:00',
    launch_timezone: 'America/New_York',
    pricing_type: 'lifetime',
    price_text: '$37 Lifetime Deal',
    rating: 4.9,
    editor_score: 9.6,
    current_rank: 23,
    affiliate_network: 'jvzoo',
    is_featured: true,
    is_trending: true,
    is_top_pick: false,
    status: 'published',
    seo_title: 'FacelessForge AI Review | DailySoftwareAI',
    seo_description: 'Andrew Darius FacelessForge AI review. Automate faceless viral videos easily.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date().toISOString(),
    categories: [CATEGORIES.aiTools, CATEGORIES.businessMarketing],
    affiliate_links: [
      {
        id: 'link-023',
        product_id: 'p023-facelessforge-ai',
        network: 'jvzoo',
        url: 'https://jvz4.com/c/3374691/445415',
        status: 'active',
        is_primary: true,
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'p024-kids-learning-game',
    name: 'AI Kids Learning Game Builder',
    slug: 'ai-kids-learning-game-builder',
    tagline: 'No-Code AI Educational Game & Puzzle Generator for Kids',
    short_description: 'Laxman Singh’s no-code builder for creating interactive educational web and mobile games for children.',
    full_description: 'AI Kids Learning Game Builder produces math puzzles, vocabulary games, logic challenges, and printable game boards for monetized web portals.',
    logo_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=150&q=80',
    featured_image_url: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=1200&q=80',
    official_website_url: 'https://launchpadjv.com/o/390/21932',
    launch_date: '2026-07-21',
    launch_time: '10:00:00',
    launch_timezone: 'America/New_York',
    pricing_type: 'lifetime',
    price_text: '$27 Launch Deal',
    rating: 4.7,
    editor_score: 9.3,
    current_rank: 24,
    affiliate_network: 'launchpad',
    is_featured: false,
    is_trending: false,
    is_top_pick: false,
    status: 'published',
    seo_title: 'AI Kids Learning Game Builder Review | DailySoftwareAI',
    seo_description: 'Laxman Singh AI Kids Learning Game Builder review. Build educational games without coding.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date().toISOString(),
    categories: [CATEGORIES.softwareApps, CATEGORIES.aiTools],
    affiliate_links: [
      {
        id: 'link-024',
        product_id: 'p024-kids-learning-game',
        network: 'launchpad',
        url: 'https://launchpadjv.com/o/390/21932',
        status: 'active',
        is_primary: true,
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'p1111111-1111-1111-1111-111111111111',
    name: 'ChatPulse AI',
    slug: 'chatpulse-ai',
    tagline: 'Autonomous AI Support Agents for Next-Gen Customer Success',
    short_description: 'Deploy intelligent AI support agents that handle 80%+ of customer tickets in seconds with human-level accuracy.',
    full_description: 'ChatPulse AI empowers SaaS businesses, e-commerce stores, and digital agencies to automate support workflows seamlessly. By connecting directly to your knowledge bases, help docs, and API endpoints, ChatPulse resolves complex customer inquiries in over 50 languages with minimal supervision.',
    logo_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=150&q=80',
    featured_image_url: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80',
    official_website_url: 'https://chatpulse.ai',
    launch_date: new Date().toISOString().split('T')[0],
    launch_time: '09:00:00',
    launch_timezone: 'America/New_York',
    pricing_type: 'freemium',
    price_text: 'From $29/mo (Free 14-day trial)',
    rating: 4.9,
    editor_score: 9.7,
    current_rank: 25,
    affiliate_network: 'direct',
    is_featured: true,
    is_trending: true,
    is_top_pick: false,
    status: 'published',
    seo_title: 'ChatPulse AI Review 2026: Features, Pricing & Best Deals | DailySoftwareAI',
    seo_description: 'In-depth review of ChatPulse AI: autonomous customer support agent platform.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date().toISOString(),
    categories: [CATEGORIES.aiTools],
    affiliate_links: [
      {
        id: 'link-chatpulse',
        product_id: 'p1111111-1111-1111-1111-111111111111',
        network: 'direct',
        url: 'https://chatpulse.ai/?ref=dailysoftwareai',
        status: 'active',
        is_primary: true,
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'p2222222-2222-2222-2222-222222222222',
    name: 'RankBoost SEO Pro',
    slug: 'rankboost-seo-pro',
    tagline: 'AI-Powered SEO Audits, Content Optimization & Rank Tracking',
    short_description: 'All-in-one SEO platform designed to uncover high-converting keywords and generate search-optimized articles in minutes.',
    full_description: 'RankBoost SEO Pro combines deep SERP analysis with advanced natural language processing. It pinpoints low-competition keyword opportunities, audits technical site health, and suggests real-time content improvements to help your site dominate search engine rankings.',
    logo_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=150&q=80',
    featured_image_url: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80',
    official_website_url: 'https://rankboostpro.com',
    launch_date: new Date(Date.now() - 86400000 * 2).toISOString().split('T')[0],
    launch_time: '10:00:00',
    launch_timezone: 'UTC',
    pricing_type: 'paid',
    price_text: '$49/mo or $399/year',
    rating: 4.7,
    editor_score: 9.3,
    current_rank: 26,
    affiliate_network: 'jvzoo',
    is_featured: true,
    is_trending: true,
    is_top_pick: false,
    status: 'published',
    seo_title: 'RankBoost SEO Pro Review & Special Deal | DailySoftwareAI',
    seo_description: 'Read our complete review of RankBoost SEO Pro. Uncover keyword opportunities easily.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date().toISOString(),
    categories: [CATEGORIES.seo],
    affiliate_links: [
      {
        id: 'link-rankboost',
        product_id: 'p2222222-2222-2222-2222-222222222222',
        network: 'jvzoo',
        url: 'https://jvzoo.com/c/12345/rankboost',
        status: 'active',
        is_primary: true,
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'p3333333-3333-3333-3333-333333333333',
    name: 'FlowAutomate AI',
    slug: 'flowautomate-ai',
    tagline: 'No-Code Visual Workflow Builder with Native AI Integration',
    short_description: 'Connect 1,000+ apps, trigger complex conditional branches, and run AI processing pipelines without writing code.',
    full_description: 'FlowAutomate AI simplifies enterprise and small business automation. Build custom multi-step triggers, transform JSON payloads on the fly, and embed LLM reasoning directly into your existing business software stack.',
    logo_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=150&q=80',
    featured_image_url: 'https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?auto=format&fit=crop&w=1200&q=80',
    official_website_url: 'https://flowautomate.io',
    launch_date: new Date(Date.now() + 86400000).toISOString().split('T')[0],
    launch_time: '14:00:00',
    launch_timezone: 'America/Los_Angeles',
    pricing_type: 'lifetime',
    price_text: '$67 One-Time Lifetime Deal',
    rating: 4.8,
    editor_score: 9.5,
    current_rank: 27,
    affiliate_network: 'warriorplus',
    is_featured: true,
    is_trending: false,
    is_top_pick: false,
    status: 'published',
    seo_title: 'FlowAutomate AI Lifetime Deal & Review | DailySoftwareAI',
    seo_description: 'Get the FlowAutomate AI lifetime deal. Visual workflow builder with built-in AI.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    published_at: new Date().toISOString(),
    categories: [CATEGORIES.automation],
    affiliate_links: [
      {
        id: 'link-flowautomate',
        product_id: 'p3333333-3333-3333-3333-333333333333',
        network: 'warriorplus',
        url: 'https://warriorplus.com/o2/a/flowautomate/0',
        status: 'active',
        is_primary: true,
        created_at: new Date().toISOString(),
      },
    ],
  },
];
